# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Elizabeth Santorella
tagline:          ''
description:      ''
baseurl:          /

author:
  name:           'Elizabeth Santorella'
  url:             http://esantorella.com/
paginate:         5
paginate_path: "/Posts/page:num"

# Custom vars
version:          3.3.0

github:           
  repo:           https://github.com/esantorella
