# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Elizabeth Santorella
tagline:          ''
description:      'a person with a website'
url:              esantorella.com
baseurl:          /

author:
  name:           'Elizabeth Santorella'
  url:             http://esantorella.com
paginate:         5
paginate_path: "/Posts/page:num"

# Custom vars

github:           
  repo:           https://github.com/esantorella
